### ISSUE TITLE
Seek plots of all predictions on three datasets (CoCA,CoSal2015,CoSOD3k)

### ISSUE THREAD

**Issue by jinghuaipan** [sourachakra/SCoSPARC#2]
Hi, I have read your article carefully and I think it is a high level article. In addition, I would like to obtain your prediction result graphs on three datasets (CoCA,CoSal2015,CoSOD3k). When I tried to download your prediction result graphs on your github website, I found that the URL of the prediction graph was not open, could you please upload the prediction significance graph link again? Thank you very much!

**Comment by Gi-gigi** [comment]
非常感谢，请您重新上传一下预测图~ 谢谢您！

**Comment by sourachakra** [comment]
Hello, thank you for your kind feedback! The code has been released and the co-saliency maps are now available for download on the three test datasets. Thanks.
